# Generated by Django 4.1.7 on 2023-03-02 17:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.TextField()),
                ('imagenURI', models.TextField(null=True)),
                ('nombre', models.TextField()),
                ('cantidad', models.IntegerField(default=0)),
                ('fechaRegistro', models.TextField()),
                ('ultimaFechaActualizacion', models.TextField()),
                ('sincronizado', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='LogArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.TextField()),
                ('fechaRegistro', models.TextField()),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.articulo')),
            ],
        ),
    ]
