# Generated by Django 4.1.7 on 2023-03-03 00:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_articulo_sincronizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='fechaRegistro',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='sincronizado',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 0, 18, 11, 977387, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='ultimaFechaActualizacion',
            field=models.DateTimeField(),
        ),
    ]
