# Generated by Django 4.1.7 on 2023-03-03 01:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_alter_articulo_fecharegistro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='sincronizado',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 1, 31, 30, 994060, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='sku',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
