# Generated by Django 4.1.7 on 2023-03-03 01:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_alter_articulo_sincronizado_alter_articulo_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='product_id',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articulo',
            name='sincronizado',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 1, 38, 57, 116726, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='sku',
            field=models.CharField(max_length=50),
        ),
    ]
