# Generated by Django 4.1.7 on 2023-03-03 01:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_articulo_product_id_alter_articulo_sincronizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='sincronizado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
