# Generated by Django 4.1.7 on 2023-03-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encabezado',
            name='fechaActualizacion',
            field=models.DateTimeField(null=True),
        ),
    ]
