# Generated by Django 4.1.7 on 2023-03-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_alter_encabezado_fechaactualizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='encabezado',
            name='orden_id',
            field=models.CharField(default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='encabezado',
            name='numeroOrden',
            field=models.CharField(max_length=50),
        ),
    ]
