# Generated by Django 4.1.7 on 2023-03-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_encabezado_orden_id_alter_encabezado_numeroorden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='product_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
