# Generated by Django 4.1.7 on 2023-03-06 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_detalle_imagenuri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.TextField(default=''),
        ),
    ]
